variable "reg_name" {}
variable "vpc_cidr_block" {}
variable "vpc_tags" {}
variable "subnet_cidr_block" {}
variable "subnet_az" {}
variable "subnet_tag" {}
variable "igw_tag" {}
variable "rt_cidr_block" {}
variable "rt_tag" {}
variable "ec2_ami" {}
variable "ec2_az" {}
variable "ec2_type" {}
variable "key_name" {}
variable "ec2_tag" {}
